audio = "Portal 2 - All Cave Johnson Quotes Chopped.wav"
transcription = "Welcome, gentlemen, to Aperture Science. Astronauts, war heroes, Olympians, you're here because we want the best. And you are it. So, who is ready to make some science? Ha ha!"
